name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
# Update 'Job name' and 'working_directory' as needed based on the module structure.
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.3.7
    with:
      working_directory: './examples/complete/'
  
# Seperate Job for TFlint workflow call
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@1.3.7
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
